name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Exécuter la CI/CD uniquement sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t chablucas/docker-node-cicd:latest .
          docker push chablucas/docker-node-cicd:latest
